### ISSUE TITLE
关于航空发动机寿命预测问题请教一下

### ISSUE THREAD

**Issue by xiyueyun** [Zero-coder/FECAM#14]
您好 之前请教过您关于航空发动机剩余寿命预测的问题
![image](https://user-images.githubusercontent.com/85719567/225851965-9e4547b4-af03-4829-85ab-7b921d4a7460.png)
我是想用这个结构来做航空发动机的寿命预测 ,想把您的模块加在Encoder的后边，请问是否可以？在修改代码的过程中，不太确定self.dct_layer = dct_channel_block( ) 和result = self.dct_layer( )的入参是如何确定的？能否请作者讲解一下？谢谢您

**Comment by Zero-coder** [comment]
您好可以的,这里我的写法原因，可能产生了误解，代码里面默认的channel=96其实代表了数据的length维，一般数据shape都是（b,c,l）或者(b,l,c)，具体shape请根据代码运行内部的Shape确定。
根据您的上传的图，我假设你的输入shape为（b,c,l）
加入流程如下：
1.在model.py中加入“from layers.dctnet import dct_channel_block,dct”
2.在模型定义中加入
```
class Model(nn.Module):#
    def __init__(self,configs):
   ...
   ...
self.dct_layer=dct_channel_block(self.seq_len)//加入这段代码，self.seq_len代表了输入长度
result = self.dct_layer(last_ouput_from_residual)//last_ouput_from_resnet是您模块中的残差模块的结果
```
[dct_channel_block中把数据的shape详细的解释了](https://github.com/Zero-coder/FECAM/blob/main/layers/dctnet.py#:~:text=class-,dct_channel_block,-(nn.)

**Comment by xiyueyun** [comment]
您好 我试着把这个模型加入到代码里面了 但是效果并不是很理想 没有之前的结果好 请问可以从哪些方面考虑呢？

**Comment by xiyueyun** [comment]
> 
您好 按照您说的需要加入两行代码:
第一行是:self.dct_layer = dct_channel_lock(self.seq_len),第二行代码是result = self.dct_layer(last_ouput_from_residual)
其中您说self.seq_len代表了输入长度,不太明白这个输入长度是什么意思呢？是数据的length维还是说什么呢？
还有您说last_ouput_from_resnet是您模块中的残差模块的结果，是如下截图的意思吗？我把encoder的结果直接作为dct_layer层的输入吗? 谢谢您！
![image](https://user-images.githubusercontent.com/85719567/232206659-05e6b280-ee2f-49c1-8743-70b122c91733.png)

**Comment by Zero-coder** [comment]
> 其中您说self.seq_len代表了输入长度,不太明白这个输入长度是什么意思呢？是数据的length维还是说什么呢？

对的，您理解的正确。

> 还有您说last_ouput_from_resnet是您模块中的残差模块的结果，是如下截图的意思吗？我把encoder的结果直接作为dct_layer层的输入吗? 谢谢您！

是的，您理解的正确。
