### ISSUE TITLE
代码运行报错

### ISSUE THREAD

**Issue by CoolCodeLvs** [Zero-coder/FECAM#15]
您好，在的decnet.py中运行示例程序，发现在42行出现张量维度不匹配的问题，请问如何修改呢？是程序本身的问题吗？
![image](https://user-images.githubusercontent.com/60374558/229285578-c6e6bb77-ca2a-4942-8a04-bef361291b0a.png)

**Comment by timecoderr** [comment]
您好，请问您解决了吗？我遇到了同样的问题
