### ISSUE TITLE
关于实验效果不理想的问题

### ISSUE THREAD

**Issue by xiyueyun** [Zero-coder/FECAM#16]
您好,非常感谢您的工作,之前已经请教过您一些关于航空发动机寿命预测的问题，您的回答都很详细也很有帮助。之前请教的是模块如何添加并且加在哪里的问题。现在的问题是模块加进去效果不太理想，我不知道要从哪几个方面进行调整。请问您能否给出相关的建议呢？
下面是我的代码以及相关说明:
![image](https://github.com/Zero-coder/FECAM/assets/85719567/daa57202-a9de-468d-899f-7e4799990ccd)
由于我的数据集的特征是14个，所以我将这里的入参改成14
![image](https://github.com/Zero-coder/FECAM/assets/85719567/282b7781-e6ce-46eb-aec6-ec915c68bc3d)
同时也将这里改成了14
![image](https://github.com/Zero-coder/FECAM/assets/85719567/9de54ac6-6313-4777-bffa-7d6d72728b6d)
这个是将FECAM加入到了encoder后面，之后又跟了全连接层的代码

期待您的回复 谢谢！

**Comment by Zero-coder** [comment]
您好，可能是会有过拟合的问题，这种时候可能从网络上不太好解决，我建议可以考虑一下用：https://github.com/Zero-coder/RevIN 这种基于统计学理论的深度学习方法，为了让输入和输出分部更相符的一种方法，相对来说，有一定改观的可能性更大。

**Comment by xiyueyun** [comment]
好的 谢谢您 我将您的代码加入到了 我的代码中  
代码如下图所示:
![image](https://github.com/Zero-coder/FECAM/assets/85719567/f7bc3565-8cb7-4c04-99d9-b14c01f1bd3f)
但是结果也没有很好 请问加的地方是否有什么要求呢？

**Comment by Zero-coder** [comment]
您好，一般使用方式是这样的，`self.revin_layer('norm')`是放在整个模型输入的最前沿，最原始输入的地方 也就是模型输入的最前面，然后`self.revin_layer('denorm')`，是模型的最终输出的地方。

**Comment by xiyueyun** [comment]
您好 谢谢您 按照您提的建议试了一下 但是结果还是不是很理想

**Comment by Zero-coder** [comment]
> 您好 谢谢您 按照您提的建议试了一下 但是结果还是不是很理想

好趴，我一般用revin效果会有一丢丢的提升还是比较稳定的。revin 是ICLR2022的工作，我当时试了一下，效果还是可以的，因为底层逻辑是基于统计学，比较solid.

**Comment by wdw991107** [comment]
@xiyueyun 你好，我是跟你做同一个方向的，我有些问题能不能请教下你

**Comment by 1229308805** [comment]
在问题 #14 中，作者说了模型需要的channel参数 实际上应该是seq_length,所以你这里定义dct_channel_block（）时，参数不应该写特征数量14吧，不过作者也没给你指出来，我现在也有点迷糊
