### ISSUE TITLE
你好，我是用您的代码出现了这个问题，请问要怎么解决呢

### ISSUE THREAD

**Issue by loveciel** [Zero-coder/FECAM#18]

**Comment by loveciel** [comment]
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [32, 96, 6]], which is output 0 of DivBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by Zero-coder** [comment]
建议您先尝试运行通Autoformer，再运行我这个就应该没问题了。Autoformer里面讨论很多，应该能结局您的问题，我估计您这个是版本问题。

**Comment by Zero-coder** [comment]
https://github.com/thuml/Autoformer[https://github.com/thuml/Autoformer](url)

**Comment by Zero-coder** [comment]
https://github.com/thuml/Autoformer
