### ISSUE TITLE
A question about decomposition

### ISSUE THREAD

**Issue by 943fansi** [Zero-coder/FECAM#7]
@Zero-coder Thanks for your great work. From the perspective of time series decomposition, in addition to Fourier transform, there are also modal decomposition methods, such as empirical mode decomposition, variational mode decomposition, etc. Have you tried using mode decomposition and deep network for fusion?

**Comment by Zero-coder** [comment]
Thanks for your great question,to answer your question,I have not tried these methods yet,but I think it's a promising direction to follow and try.I think mode decomposition is a useful technique for decomposing a signal into its intrinsic modes. By doing this, we can better understand the underlying structure of the signal and identify important features or patterns. This information can be useful in a variety of applications, including time series analysis.

In terms of combining mode decomposition with deep learning, there is some potential for using these techniques together to improve performance. For example, mode decomposition could be used to pre-process the data and extract important features, which could then be fed into a deep learning model for further analysis. This could potentially allow the model to learn more effectively and make more accurate predictions. However, the effectiveness of this approach would depend on the specific problem at hand and would need to be evaluated on a case-by-case basis.

If you have any further  discuss,you can have my  contact information jiangmaowei@sia.cn,thank you again for your good question.

**Comment by Zero-coder** [comment]
**empirical mode decomposition + DL**
Combining empirical mode decomposition with deep learning for time series forecasting is an interesting idea, and there is some potential for this approach to improve the accuracy of forecast models. Empirical mode decomposition (EMD) is a method for decomposing a signal into a set of intrinsic modes, which are assumed to be either stationary or slowly-varying. By decomposing the signal in this way, we can better understand the underlying structure of the data and identify important features or patterns.

One potential use of EMD in time series forecasting is to pre-process the data and extract important features using EMD. These features could then be fed into a deep learning model, which could learn to make predictions based on the extracted features. This could potentially improve the accuracy of the forecasts, as the deep learning model would be able to learn more effectively from the pre-processed data.

It's worth noting, however, that the effectiveness of this approach would depend on the specific problem at hand and would need to be evaluated through experimentation. There is no guarantee that combining EMD with deep learning will always improve the accuracy of time series forecasts, but it is a promising approach that is worth exploring further.

**Comment by Zero-coder** [comment]
**variational mode decomposition+DL**
Yes,of course,it's worth trying combine VMD and DL together for TSF tasks.
Variational mode decomposition (VMD) is a method for decomposing a signal into a set of intrinsic modes. It is a type of modal decomposition, which is a technique used in signal processing to break a signal down into its underlying components or modes.

VMD is an extension of empirical mode decomposition (EMD), which is another popular method for modal decomposition. Like EMD, VMD decomposes a signal into a set of intrinsic modes that are assumed to be either stationary or slowly-varying. However, VMD uses a different mathematical framework, based on variational calculus, to perform the decomposition. This framework allows VMD to better handle nonlinear and non-stationary signals, which can be difficult to analyze using other methods.

VMD has a number of potential applications, including time series analysis, signal denoising, and pattern recognition. It can be used in combination with other techniques, such as deep learning, to improve performance in these applications. VMD is a useful tool for signal processing and can provide valuable insights into the underlying structure of a signal.So it;s very worthy trying to generalize those modal decomposion method into neural network for further  experiments.

**Comment by Zero-coder** [comment]
By the way,would you mind telling me through what channels you are aware of our work? Thank you very much.

**Comment by 943fansi** [comment]
@Zero-coder. I obtained frontiers by searching keywords on the arxiv website, and I provided the addresses and code links of several papers in this repository[Time-Series-Forecasting-and-Deep-Learning](https://github.com/DaoSword/Time-Series-Forecasting-and-Deep-Learning).
Last but not least, thank you very much for your serious and detailed answer!

**Comment by Zero-coder** [comment]
It's my pleasure!thank you for your careful answer!
